# Source: kubernetes-replicator/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-replicator
  namespace: kube-system
  labels:
    helm.sh/chart: kubernetes-replicator-2.12.2
    app.kubernetes.io/name: kubernetes-replicator
    app.kubernetes.io/instance: kubernetes-replicator
    app.kubernetes.io/version: "v2.12.2"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
