apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: flox-manifests
pipeline:
  mutators:
    - image: ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.2
      configPath: setters.yaml
---
apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: git
spec:
  manifest:
    version: 1
    install:
      git:
        pkg-path: git
      git-town:
        pkg-path: git-town
      gitflow:
        pkg-path: gitflow
      gh:
        pkg-path: gh
    profile:
      common: |
        if [ -d "${FLOX_ENV_PROJECT}/.github" ]; then
          gh_login=""
          if [ -n "${GH_TOKEN:-}" ]; then
            gh_login=$(gh api user --jq '.login' 2>/dev/null || true)
          elif command -v pass >/dev/null 2>&1; then
            gh_secret=$(pass show coding/github@work 2>/dev/null | head -n 1 || true)
            if [ -n "${gh_secret}" ]; then
              gh_login=$(env GH_TOKEN="${gh_secret}" gh api user --jq '.login' 2>/dev/null || true)
            fi
          fi
          if [ -n "${gh_login}" ]; then
            remote=$(git -C "${FLOX_ENV_PROJECT}" remote get-url origin 2>/dev/null || true)
            if [ -n "${remote}" ]; then
              owner=$(printf '%s' "${remote}" | cut -d'/' -f 4)
              repo_name=$(printf '%s' "${remote}" | cut -d'/' -f 5 | cut -d'.' -f 1)
              export GITHUB_LOGIN="${gh_login}"
              export GITHUB_OWNER="${owner}"
              export GITHUB_REPOSITORY="${owner}/${repo_name}"
            fi
          fi
        fi
    include:
      environments:
        - dir: /var/lib/gits/nxmatic/fleet-manifests/flox/keyhole # kpt-set: ${fleet-base-dir}/keyhole
    options: {}
  env:
    name: git
    version: 1
---
apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: home
spec:
  manifest:
    version: 1
    install:
      direnv:
        pkg-path: direnv
      linux-builder:
        pkg-path: darwin.linux-builder
        systems:
          - aarch64-darwin
      lldpd:
        pkg-path: lldpd
    options:
      systems:
        - aarch64-darwin
        - aarch64-linux
    profile:
      common: |
        mvnw_path="${FLOX_ENV_PROJECT}/mvnw"
        if [ -x "${mvnw_path}" ]; then
          maven_user_config="${FLOX_ENV_PROJECT}/.m2"
          mkdir -p "${maven_user_config}"
          export MAVEN_USER_CONFIG="${maven_user_config}"
          export MAVEN_SETTINGS="${MAVEN_USER_CONFIG}/settings.xml"

          if [ -n "${MAVEN_ARGS:-}" ]; then
            case " ${MAVEN_ARGS} " in
              *"--settings="*) ;;
              *) export MAVEN_ARGS="${MAVEN_ARGS} --settings=${MAVEN_SETTINGS}" ;;
            esac
          else
            export MAVEN_ARGS="--settings=${MAVEN_SETTINGS}"
          fi

          if [ -d "${FLOX_ENV_PROJECT}/.mvnrepository" ]; then
            export MAVEN_LOCAL_REPOSITORY="${FLOX_ENV_PROJECT}/.mvnrepository"
          elif [ -d "${FLOX_ENV_PROJECT}/.m2/repo" ]; then
            export MAVEN_LOCAL_REPOSITORY="${FLOX_ENV_PROJECT}/.m2/repo"
          fi

          maven_version_output=$("${mvnw_path}" -N -q -DmavenVersion=3.9.9 \
            -Dexpression=maven.version -Doutput=/dev/stdout help:evaluate 2>/dev/null | grep -v '^\[.*\]' | tail -n 1)
          if [ -n "${maven_version_output}" ]; then
            export MAVEN_VERSION="${maven_version_output}"
          fi
        fi
    include:
      environments:
        - dir: /var/lib/gits/nxmatic/fleet-manifests/flox/xdg # kpt-set: ${fleet-base-dir}/xdg
        - dir: /var/lib/gits/nxmatic/fleet-manifests/flox/keyhole # kpt-set: ${fleet-base-dir}/keyhole
  env:
    name: home
    version: 1
---
apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: k8s
spec:
  manifest:
    version: 1
    install:
      ceph-client:
        pkg-path: ceph-client
        pkg-group: kubectl-tools
        systems:
          - aarch64-linux
      cilium-cli:
        pkg-path: cilium-cli
        pkg-group: kubectl-tools
      dasel:
        pkg-path: dasel
        version: ^2.8.1
        pkg-group: yaml-tools
      etcdctl:
        pkg-path: etcdctl
        version: ^3.3.27
        pkg-group: etcd-tools
      fluxcd:
        pkg-path: fluxcd
        pkg-group: kubectl-tools
      helmfile:
        pkg-path: helmfile
        pkg-group: kubectl-tools
      kubernetes-helm:
        pkg-path: kubernetes-helm
        pkg-group: kubectl-tools
      kubectl:
        pkg-path: kubectl
        pkg-group: kubectl-tools
      krew:
        pkg-path: krew
        pkg-group: kubectl-tools
      kubectl-ai:
        pkg-path: kubectl-ai
        pkg-group: kubectl-plugins
      kubectl-ktop:
        pkg-path: kubectl-ktop
        pkg-group: kubectl-plugins
      kubectl-neat:
        pkg-path: kubectl-neat
        pkg-group: kubectl-plugins
      kubectl-tree:
        pkg-path: kubectl-tree
        pkg-group: kubectl-plugins
      kubectl-graph:
        pkg-path: kubectl-graph
        pkg-group: kubectl-plugins
      kubecectl-doctor:
        pkg-path: kubectl-doctor
        pkg-group: kubectl-plugins
      kubectl-explore:
        pkg-path: kubectl-explore
        pkg-group: kubectl-plugins
      kubectl-rook-ceph:
        pkg-path: kubectl-rook-ceph
        pkg-group: kubectl-plugins
      kubectl-view-secret:
        pkg-path: kubectl-view-secret
        pkg-group: kubectl-plugins
      tubekit:
        pkg-path: tubekit
        pkg-group: kubectl-tools
      yq-go:
        pkg-path: yq-go
        pkg-group: yaml-tools
      kpt:
        pkg-path: kpt
        pkg-group: kpt-tools
    options:
      systems:
        - aarch64-darwin
        - aarch64-linux
  env:
    name: k8s
    version: 1
---
apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: keyhole
spec:
  manifest:
    version: 1
    install:
      age:
        pkg-path: age
      ssh-to-age:
        pkg-path: ssh-to-age
      keychain:
        pkg-path: keychain
      gnupg:
        pkg-path: gnupg
      pass:
        pkg-path: pass
      sops:
        pkg-path: sops
    profile:
      common: |
        if [[ -r $XDG_STATE_HOME/ssh-keys.d/github_signing ]]; then
          set -a
          SOPS_AGE_KEY="$( ssh-to-age -private-key < $XDG_STATE_HOME/ssh-keys.d/github_signing )"
          set +a
        fi
    options: {}
  env:
    name: keyhole
    version: 1
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git.yaml
  - home.yaml
  - k8s.yaml
  - keyhole.yaml
  - lima.yaml
  - nix.yaml
---
apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: lima
spec:
  manifest:
    version: 1
    install:
      lima:
        pkg-path: lima
      vmnet:
        pkg-path: darwin.apple_sdk.frameworks.vmnet
    options:
      systems:
        - aarch64-darwin
        - x86_64-darwin
  env:
    name: lima
    version: 1
---
apiVersion: flox.dev/v1alpha1
kind: FloxEnvironment
metadata:
  name: nix
spec:
  manifest:
    version: 1
    install:
      nixd:
        pkg-path: nixd
      nix-tree:
        pkg-path: nix-tree
      nixfmt-rfc-style:
        pkg-path: nixfmt-rfc-style
      statix:
        pkg-path: statix
      deadnix:
        pkg-path: deadnix
      nix-output-monitor:
        pkg-path: nix-output-monitor
      nix-eval-jobs:
        pkg-path: nix-eval-jobs
      cachix:
        pkg-path: cachix
      watchexec:
        pkg-path: watchexec
      nvfetcher:
        pkg-path: nvfetcher
      nix-fast-build:
        pkg-path: nix-fast-build
    include:
      environments:
        - dir: /var/lib/gits/nxmatic/fleet-manifests/flox/keyhole # kpt-set: ${fleet-base-dir}/keyhole
    options: {}
  env:
    name: nix
    version: 1
---
apiVersion: fn.kpt.dev/v1alpha1
kind: ApplySetters
metadata:
  name: fleet-base-dir
data:
  fleet-base-dir: /var/lib/gits/nxmatic/fleet-manifests/flox
