apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata: # kpt-merge: porch-system/bioskop-catalog
  name: bioskop-catalog
  namespace: porch-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|Repository|porch-system|bioskop-catalog'
spec:
  description: Catalog of curated kpt packages tracked in incus-rke2-cluster
  type: git
  git:
    repo: https://github.com/nxmatic/incus-rke2-cluster.git
    branch: develop
    directory: modules/nixos/incus-rke2-cluster/kpt/catalog
    secretRef:
      name: github-token
  deployment: true
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata: # kpt-merge: porch-system/bioskop-state
  name: example-state # kpt-set: ${cluster-state-repo}
  namespace: porch-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|Repository|porch-system|bioskop-state'
spec:
  description: Rendered Porch package state for bioskop cluster
  type: git
  git:
    repo: https://github.com/nxmatic/fleet.git
    branch: main # kpt-set: ${cluster-state-branch}
    directory: packagevariants/example # kpt-set: ${cluster-state-directory}
    createBranch: true
    secretRef:
      name: github-token
  deployment: true
