# Source: flux-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-operator
  namespace: flux-system
  labels:
    helm.sh/chart: flux-operator-0.36.0
    app.kubernetes.io/name: flux-operator
    app.kubernetes.io/instance: flux-operator
    app.kubernetes.io/version: "v0.36.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
