apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /flux-instance-setters
  name: flux-instance-setters
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/function-config: apply-setters
    description.kpt.dev: Sample Flux Instance Helm setters; override downstream with real values
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|flux-instance-setters'
data:
  helm-repo: oci://ghcr.io/controlplaneio-fluxcd/charts
  chart-name: flux-instance
  chart-version: 0.36.0
  release-name: flux-instance
  target-namespace: flux-system
  distribution-version: "2.x"
  distribution-registry: ghcr.io/fluxcd
  distribution-artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest
  sync-interval: 1m
  sync-url: https://github.com/nxmatic/fleet.git
  sync-ref: rke2-subtree
  sync-path: bioskop
  cluster-type: kubernetes
  cluster-size: ""
  cluster-domain: cluster.local
