apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: bioskop-catalog
  namespace: porch-system
spec:
  description: Catalog of curated kpt packages tracked in incus-rke2-cluster
  type: git
  git:
    repo: https://github.com/nxmatic/incus-rke2-cluster.git
    branch: develop
    directory: modules/nixos/incus-rke2-cluster/kpt/catalog
    secretRef:
      name: github-token
  deployment: true
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: bioskop-state # kpt-set: ${cluster-state-repo}
  namespace: porch-system
spec:
  description: Rendered Porch package state for bioskop cluster
  type: git
  git:
    repo: https://github.com/nxmatic/fleet-manifests.git
    branch: rke2-subtree # kpt-set: ${cluster-state-branch}
    directory: packagevariants/bioskop # kpt-set: ${cluster-state-directory}
    createBranch: true
    secretRef:
      name: github-token
  deployment: true
